version: "3"

services:
  db:
    build: .
    container_name: cursonestjs-db
    restart: always
    tty: true
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: cursonestjs-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=matheus.silva@compasso.com.br
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "8001:80"
    depends_on:
      - db
volumes:
  reserved:
networks:
    postgres-network:
       driver: bridge